function setNameAndInputDims(fileName, modelName, dims)

s = sprintf(['' ...
    'name: "%s"\n\n' ...
    'input: "data"\n' ...
    'input_dim: %i\n' ...
    'input_dim: %i\n' ...
    'input_dim: %i\n' ...
    'input_dim: %i\n\n'], ...
    modelName, dims(1),dims(2),dims(3),dims(4));

fStr = fileread(fileName);
f = fopen([fileName '_tmp'],'w');
fprintf(f,'%s%s',s,fStr);
fclose(f);


